AllCops:
  # can opt-in to new cops by default by adding this
  NewCops: enable
  Include:
    - '**/Gemfile'
    - '**/Rakefile'
    - '**/config.ru'
    - '**/*.rb'
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'node_modules/**/*'
    - 'script/**/*'
    - 'vendor/**/*'
    - 'spec/spec_helper.rb'
    - 'spec/features_helper.rb'
    - 'spec/rails_helper.rb'
    - Guardfile
    - Gemfile
    - app/helpers/application_helper.rb

require: rubocop-rails

Layout/LineLength:
  Max: 120

Layout/ParameterAlignment:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/OptionalBooleanParameter:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: 'consistent_comma'

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: 'consistent_comma'

Style/TrailingCommaInBlockArgs:
  Enabled: true

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: 'consistent_comma'

Style/RedundantSelf:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/Next:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

HasAndBelongsToMany:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false
