language: ruby
-dist: focal # temporary fix for https://github.com/rvm/rvm/issues/5133
bundler_args: --without development production
sudo: false
# rvm:
#   - 3.0.1

services:
  - postgresql

addons:
  postgresql: '13.4'
  chrome: stable

install:
  # rvm
  - curl -sSL https://raw.githubusercontent.com/rvm/rvm/master/binscripts/rvm-installer | bash -s stable
  - rvm reload && rvm install 3.0.1

  # chromedriver
  - wget -N http://chromedriver.storage.googleapis.com/2.30/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver

  # rubygems
  - gem install bundler --version 2.1.4
  - bundle install

  # webpack
  - nvm install 14
  - node -v
  - npm i -g yarn
  - yarn

before_script:
    # - psql -c 'create database travis_ci_test;' -U postgres
    - psql -c 'CREATE DATABASE travis_ci_test;' -U postgres -p 5433
    - mv config/database.yml.test config/database.yml
    - RAILS_ENV=test bundle exec rake db:setup --trace

script:
  - bundle exec rspec spec --format progress
  - bundle exec brakeman
  - bundle exec rubocop -E

cache:
  bundler: true
