language: ruby
-dist: focal # temporary fix for https://github.com/rvm/rvm/issues/5133
bundler_args: --without development production
sudo: false
# rvm:
#   - 3.0.1

services:
  - postgresql

addons:
  # Use a different PostgreSQL version than the default:
  postgresql: 13
  apt:
    update: true
    packages:
      - postgresql-13
      - postgresql-client-13
      # - postgresql-13-postgis-3
      - postgresql-contrib
  chrome: stable

env:
  global:
    - PGPORT=5433
    - PGUSER=postgres

before_install:
  # Use trust instead of peer authentication:
  - >-
    sudo sed -i
    -e '/local.*peer/s/postgres/all/'
    -e 's/peer\|md5/trust/g'
    /etc/postgresql/13/main/pg_hba.conf
  # Restart the PostgreSQL service:
  - sudo service postgresql@13-main restart

install:
  # rvm must be manually installed on dist: focal
  - curl -sSL https://raw.githubusercontent.com/rvm/rvm/master/binscripts/rvm-installer | bash -s stable
  - rvm reload && rvm install 3.0.1

  # chromedriver
  - wget -N http://chromedriver.storage.googleapis.com/2.30/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver

  # rubygems
  - gem install bundler --version 2.1.4
  - bundle install

  # webpack
  - nvm install 14
  - node -v
  - npm i -g yarn
  - yarn

before_script:
  - sudo psql -p 5433 -U postgres -c 'create database my-app;'
  - mv config/database.yml.test config/database.yml
  - RAILS_ENV=test bundle exec rake db:setup --trace

script:
  - bundle exec rspec spec --format progress
  - bundle exec brakeman
  - bundle exec rubocop -E

cache:
  bundler: true
