language: ruby
bundler_args: --without development production
sudo: false
rvm:
  - 2.7.2

addons:
  postgresql: '9.4'
  chrome: stable

install:
  # chromedriver
  - wget -N http://chromedriver.storage.googleapis.com/2.30/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver

  # rubygems
  - gem install bundler --version 2.1.4
  - bundle install

  # webpack
  - nvm install node
  - node -v
  - npm i -g yarn
  - yarn

before_script:
    - psql -c 'create database travis_ci_test;' -U postgres
    - mv config/database.yml.test config/database.yml
    - RAILS_ENV=test bundle exec rake db:setup --trace

script:
  - bundle exec rspec spec --format progress
  - bundle exec brakeman
  - bundle exec rubocop -E

cache:
  bundler: true
