#
# [orb Search](https://circleci.com/developer/orbs?query=postgres&page=1&pageSize=15)
# [cimg search](https://circleci.com/developer/images)
# [Example config (with yarn caching, webpacker)](https://discuss.circleci.com/t/webpacker-compile-freezes-on-compile/33055)
# [Circleci provided example](https://github.com/CircleCI-Public/circleci-demo-ruby-rails/blob/master/.circleci/config.yml)
# [caching](https://circleci.com/docs/2.0/caching/)
#
version: 2.1

orbs:
  ruby: circleci/ruby@2.1.0
  node: circleci/node@5.1.1
  browser-tools: circleci/browser-tools@1.4.8
  dscar-brakeman: moneyforward/dscar-brakeman@1.2.0

jobs:
  build:
    environment:
      RAILS_ENV: test
      NODE_ENV: test
    docker:
      - image: cimg/ruby:3.3.8
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - run: ruby --version
      - ruby/install-deps
      - node/install:
          install-yarn: true
          node-version: '22.15.0'
      - run: node --version

  test:
    parallelism: 3
    docker:
      - image: cimg/ruby:3.3.8-node
      - image: cimg/node:22.15.0-browsers
      - image: cimg/postgres:17.4
        environment:
          POSTGRES_USER: benradler
          POSTGRES_DB: benradler-test
          POSTGRES_PASSWORD: ""
          POSTGRES_HOST_AUTH_METHOD: trust
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      PGHOST: 127.0.0.1
      PGUSER: benradler
      PGPASSWORD: ""
      RAILS_ENV: test
      NODE_ENV: test
      RAILS_HOST: 'http://localhost'
    steps:
      - checkout
      - ruby/install-deps
      - node/install:
          install-yarn: true
          node-version: '22.15.0'
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          command: |
            google-chrome --version
            chromedriver --version
          name: Check browsertools install

      - run:
          name: Setup dotenv
          command: cp .env.example .env

      - run:
          name: Wait for postgres to start
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: postgres setup
          command: cp config/database.yml.test config/database.yml && bundle exec rails db:schema:load --trace

      # restore yarn cache if available
      - restore_cache:
          keys:
            - yarn-{{ checksum "yarn.lock" }}

      # install node deps with yarn
      - run:
          name: Yarn install
          command: yarn install --cache-folder ~/.cache/yarn

      # save yarn cache
      - save_cache:
          key: yarn-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      # restore webpack cache if available
      - restore_cache:
          keys:
            - webpack-{{ .Revision }}

      # webpacker compilation
      - run: bin/rails shakapacker:compile

      # save webpacker cache
      - save_cache:
          key: webpack-{{ .Revision }}
          paths:
            - /home/circleci/project/public/packs-test/

      # Run rspec in parallel
      - ruby/rspec-test

      # run rubocop
      - ruby/rubocop-check

      # run brakeman
      - dscar-brakeman/analyze

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
