version: 2.1

orbs:
  ruby: circleci/ruby@1.3.0
  node: circleci/node@5.0.0
  browser-tools: circleci/browser-tools@1.2.3

jobs:
  install-ruby:
    docker:
      - image: cimg/ruby:3.1.0
    steps:
      - checkout
      - run: ruby --version
      - ruby/install-deps
      # # Store bundle cache
      # - node/install-packages:
      #     pkg-manager: yarn
      #     cache-key: "yarn.lock"

  install-node:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: '16.13'
      - run: node --version
      - run: yarn install

  test:
    parallelism: 3
    docker:
      - image: cimg/ruby:3.1.0-node
      - image: cimg/node:16.13-browsers
      - image: circleci/postgres:13.5
        environment:
          POSTGRES_USER: circleci-demo-ruby
          POSTGRES_DB: benradler-test
          POSTGRES_PASSWORD: ""
          POSTGRES_HOST_AUTH_METHOD: trust
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      PGHOST: 127.0.0.1
      PGUSER: circleci-demo-ruby
      PGPASSWORD: ""
      RAILS_ENV: test
    steps:
      - checkout
      - ruby/install-deps
      # - node/install-packages:
      #     pkg-manager: yarn
      #     cache-key: "yarn.lock"
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          command: |
            google-chrome --version
            chromedriver --version
          name: Check install
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Database setup
          command: cp config/database.yml.test config/database.yml && bundle exec rails db:schema:load --trace
      - run: bundle exec rake webpacker:compile
      # Run rspec in parallel
      - ruby/rspec-test
      - ruby/rubocop-check

workflows:
  version: 2
  build_and_test:
    jobs:
      - install-ruby
      - install-node
      - test:
          requires:
            - install-ruby
            - install-node
