default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost # postgres docker container
  username: postgres
  password: password

development:
  <<: *default
  database: benradler-development

test:
  <<: *default
  database: benradler-test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>